// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
export type Game = {
  id: bigint,
  playerBlack: Identity,
  playerWhite: Identity | undefined,
  board: string,
  turn: string,
  passes: number,
  boardSize: number,
  previousBoard: string | undefined,
  gameOver: boolean,
  finalScoreBlack: bigint | undefined,
  finalScoreWhite: bigint | undefined,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Game {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createU64Type()),
      new ProductTypeElement("playerBlack", AlgebraicType.createIdentityType()),
      new ProductTypeElement("playerWhite", AlgebraicType.createOptionType(AlgebraicType.createIdentityType())),
      new ProductTypeElement("board", AlgebraicType.createStringType()),
      new ProductTypeElement("turn", AlgebraicType.createStringType()),
      new ProductTypeElement("passes", AlgebraicType.createU8Type()),
      new ProductTypeElement("boardSize", AlgebraicType.createU8Type()),
      new ProductTypeElement("previousBoard", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
      new ProductTypeElement("gameOver", AlgebraicType.createBoolType()),
      new ProductTypeElement("finalScoreBlack", AlgebraicType.createOptionType(AlgebraicType.createU64Type())),
      new ProductTypeElement("finalScoreWhite", AlgebraicType.createOptionType(AlgebraicType.createU64Type())),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Game): void {
    Game.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Game {
    return Game.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


