name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run tests in dev container
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: |
            # Start SpacetimeDB in the background
            npm run db:start &
            # Wait for SpacetimeDB to start
            sleep 10
            # Publish module to SpacetimeDB
            npm run db:publish
            # Run tests and ensure the exit code is captured
            npm run test
            TEST_EXIT_CODE=$?
            # Kill all spacetime processes to ensure we clean up
            pkill -f spacetime || true
            # Exit with the test exit code
            exit $TEST_EXIT_CODE