name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run tests in dev container
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: |
            # Start SpacetimeDB in the background and capture its PID
            npm run db:start &
            DB_PID=$!
            
            # Ensure the background process is terminated on script exit
            trap "kill $DB_PID" SIGINT SIGTERM EXIT
            
            # Wait for SpacetimeDB to start
            sleep 10
            
            # Publish module to SpacetimeDB
            npm run db:publish
            
            # Run tests and capture the exit code
            npm run test
            TEST_EXIT_CODE=$?
            
            # Exit with the test command's exit code
            exit $TEST_EXIT_CODE