name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run tests in dev container
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: |
            npm run db:start
            # Wait for SpacetimeDB to start
            sleep 5
            # Publish our module
            npm run db:publish
            # Run the tests
            npm run test